import type { PageTheme } from "./types";

export const HEARTS = [
  {
    left: "4%",
    top: "10%",
    size: 14,
    delay: "0s",
    duration: "10.5s",
    containerClassName: "text-rose-300/50 animate-heart-drift",
    iconClassName: "animate-heart-pulse",
  },
  {
    left: "8%",
    top: "52%",
    size: 10,
    delay: "2.1s",
    duration: "9.2s",
    containerClassName: "text-pink-300/45 animate-heart-orbit",
  },
  {
    left: "13%",
    top: "75%",
    size: 22,
    delay: "1.8s",
    duration: "13s",
    containerClassName: "text-pink-300/55 animate-heart-drift",
    iconClassName: "animate-heart-pulse",
  },
  {
    left: "18%",
    top: "24%",
    size: 12,
    delay: "0.7s",
    duration: "8.4s",
    containerClassName: "text-rose-200/50 animate-heart-orbit",
  },
  {
    left: "24%",
    top: "12%",
    size: 16,
    delay: "1.4s",
    duration: "11.2s",
    containerClassName: "text-fuchsia-300/45 animate-heart-drift",
  },
  {
    left: "29%",
    top: "64%",
    size: 11,
    delay: "2.6s",
    duration: "9.6s",
    containerClassName: "text-pink-200/50 animate-heart-orbit",
  },
  {
    left: "36%",
    top: "18%",
    size: 20,
    delay: "0.9s",
    duration: "12.8s",
    containerClassName: "text-rose-300/55 animate-heart-drift",
    iconClassName: "animate-heart-pulse",
  },
  {
    left: "42%",
    top: "8%",
    size: 18,
    delay: "1.2s",
    duration: "12s",
    containerClassName: "text-pink-300/52 animate-heart-orbit",
  },
  {
    left: "48%",
    top: "74%",
    size: 12,
    delay: "2.9s",
    duration: "8.8s",
    containerClassName: "text-fuchsia-200/48 animate-heart-drift",
  },
  {
    left: "54%",
    top: "30%",
    size: 15,
    delay: "1.1s",
    duration: "10.2s",
    containerClassName: "text-rose-300/48 animate-heart-orbit",
  },
  {
    left: "58%",
    top: "80%",
    size: 18,
    delay: "2.4s",
    duration: "10s",
    containerClassName: "text-pink-300/55 animate-heart-drift",
  },
  {
    left: "64%",
    top: "14%",
    size: 26,
    delay: "0.4s",
    duration: "14s",
    containerClassName: "text-rose-300/56 animate-heart-drift",
    iconClassName: "animate-heart-pulse",
  },
  {
    left: "69%",
    top: "48%",
    size: 11,
    delay: "2.2s",
    duration: "8.9s",
    containerClassName: "text-pink-200/50 animate-heart-orbit",
  },
  {
    left: "74%",
    top: "22%",
    size: 14,
    delay: "1.7s",
    duration: "10.8s",
    containerClassName: "text-fuchsia-300/46 animate-heart-drift",
  },
  {
    left: "78%",
    top: "60%",
    size: 16,
    delay: "1.1s",
    duration: "9.5s",
    containerClassName: "text-rose-200/55 animate-heart-orbit",
  },
  {
    left: "84%",
    top: "16%",
    size: 19,
    delay: "2.7s",
    duration: "12.5s",
    containerClassName: "text-pink-300/52 animate-heart-drift",
  },
  {
    left: "88%",
    top: "70%",
    size: 13,
    delay: "1.5s",
    duration: "8.5s",
    containerClassName: "text-rose-300/46 animate-heart-orbit",
  },
  {
    left: "93%",
    top: "34%",
    size: 10,
    delay: "0.5s",
    duration: "9.4s",
    containerClassName: "text-pink-200/50 animate-heart-drift",
  },
  {
    left: "96%",
    top: "82%",
    size: 12,
    delay: "2.8s",
    duration: "8.7s",
    containerClassName: "text-fuchsia-200/45 animate-heart-orbit",
  },

  /* ── sway layer ── */
  {
    left: "2%",
    top: "40%",
    size: 17,
    delay: "0.3s",
    duration: "11s",
    containerClassName: "text-rose-400/42 animate-heart-sway",
  },
  {
    left: "10%",
    top: "66%",
    size: 13,
    delay: "2.4s",
    duration: "9.8s",
    containerClassName: "text-pink-300/48 animate-heart-sway",
    iconClassName: "animate-heart-pulse",
  },
  {
    left: "21%",
    top: "88%",
    size: 20,
    delay: "1.1s",
    duration: "12.4s",
    containerClassName: "text-fuchsia-300/44 animate-heart-sway",
  },
  {
    left: "40%",
    top: "86%",
    size: 15,
    delay: "3.0s",
    duration: "10.6s",
    containerClassName: "text-rose-300/50 animate-heart-sway",
    iconClassName: "animate-heart-pulse",
  },
  {
    left: "55%",
    top: "90%",
    size: 11,
    delay: "0.8s",
    duration: "9.2s",
    containerClassName: "text-pink-400/42 animate-heart-sway",
  },
  {
    left: "70%",
    top: "84%",
    size: 18,
    delay: "1.9s",
    duration: "11.8s",
    containerClassName: "text-rose-400/46 animate-heart-sway",
    iconClassName: "animate-heart-pulse",
  },
  {
    left: "85%",
    top: "88%",
    size: 14,
    delay: "0.5s",
    duration: "10.4s",
    containerClassName: "text-fuchsia-200/44 animate-heart-sway",
  },
  {
    left: "97%",
    top: "58%",
    size: 19,
    delay: "2.2s",
    duration: "12s",
    containerClassName: "text-pink-300/46 animate-heart-sway",
  },

  /* ── rise layer ── */
  {
    left: "6%",
    top: "95%",
    size: 10,
    delay: "1.6s",
    duration: "10s",
    containerClassName: "text-rose-300/40 animate-heart-rise",
  },
  {
    left: "31%",
    top: "96%",
    size: 14,
    delay: "2.8s",
    duration: "11.5s",
    containerClassName: "text-pink-300/44 animate-heart-rise",
    iconClassName: "animate-heart-pulse",
  },
  {
    left: "47%",
    top: "97%",
    size: 9,
    delay: "0.6s",
    duration: "9.6s",
    containerClassName: "text-fuchsia-300/40 animate-heart-rise",
  },
  {
    left: "63%",
    top: "95%",
    size: 16,
    delay: "1.4s",
    duration: "12.2s",
    containerClassName: "text-rose-400/42 animate-heart-rise",
    iconClassName: "animate-heart-pulse",
  },
  {
    left: "80%",
    top: "96%",
    size: 12,
    delay: "3.2s",
    duration: "10.8s",
    containerClassName: "text-pink-200/44 animate-heart-rise",
  },

  /* ── twirl layer ── */
  {
    left: "15%",
    top: "45%",
    size: 9,
    delay: "1.0s",
    duration: "11.2s",
    containerClassName: "text-rose-300/38 animate-heart-twirl",
  },
  {
    left: "50%",
    top: "58%",
    size: 12,
    delay: "2.6s",
    duration: "10.4s",
    containerClassName: "text-pink-400/40 animate-heart-twirl",
  },
  {
    left: "77%",
    top: "42%",
    size: 10,
    delay: "0.4s",
    duration: "9.8s",
    containerClassName: "text-fuchsia-300/38 animate-heart-twirl",
  },
  {
    left: "91%",
    top: "55%",
    size: 14,
    delay: "1.8s",
    duration: "12s",
    containerClassName: "text-rose-200/42 animate-heart-twirl",
    iconClassName: "animate-heart-pulse",
  },
];

export const PAGE_THEMES: PageTheme[] = [
  {
    frame: "from-rose-50/96 via-pink-50/92 to-rose-100/88",
    halo: "from-rose-300/34 via-pink-200/18 to-transparent",
    edge: "border-rose-200/55",
    chip: "bg-rose-50/88 text-rose-600",
    card: "bg-gradient-to-br from-white/78 to-rose-50/65",
  },
  {
    frame: "from-white/96 via-pink-50/92 to-fuchsia-50/88",
    halo: "from-pink-300/30 via-fuchsia-200/15 to-transparent",
    edge: "border-pink-100/60",
    chip: "bg-pink-50/85 text-pink-600",
    card: "bg-gradient-to-br from-white/78 to-pink-50/65",
  },
  {
    frame: "from-fuchsia-50/95 via-pink-50/92 to-rose-50/88",
    halo: "from-fuchsia-300/32 via-pink-200/15 to-transparent",
    edge: "border-fuchsia-200/52",
    chip: "bg-fuchsia-50/85 text-fuchsia-600",
    card: "bg-gradient-to-br from-white/78 to-fuchsia-50/60",
  },
  {
    frame: "from-amber-50/94 via-rose-50/92 to-pink-50/88",
    halo: "from-amber-200/30 via-rose-200/14 to-transparent",
    edge: "border-amber-100/55",
    chip: "bg-amber-50/85 text-amber-600",
    card: "bg-gradient-to-br from-white/78 to-amber-50/55",
  },
  {
    frame: "from-purple-50/94 via-pink-50/90 to-rose-50/88",
    halo: "from-purple-300/28 via-pink-200/14 to-transparent",
    edge: "border-purple-100/55",
    chip: "bg-purple-50/85 text-purple-600",
    card: "bg-gradient-to-br from-white/78 to-purple-50/55",
  },
  {
    frame: "from-rose-100/96 via-rose-50/92 to-pink-50/88",
    halo: "from-rose-400/32 via-pink-300/16 to-transparent",
    edge: "border-rose-200/58",
    chip: "bg-rose-100/85 text-rose-600",
    card: "bg-gradient-to-br from-white/78 to-rose-50/65",
  },
];
